trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.6'

- script: python -m pip install --upgrade pip azure-devops
  displayName: 'Install tools'

- task: PythonScript@0
  inputs:
    scriptSource: 'filePath'
    scriptPath: './IdentifyGitBuildCommitItems.py'
  env:
      SYSTEM_ACCESSTOKEN: $(System.AccessToken)

- task: PythonScript@0
  inputs:
    scriptSource: 'filePath'
    scriptPath: './FilterDeployableScripts.py'

- task: CopyFiles@2
  inputs:
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: drop